@include('components.head')
@include('components.navbar')
@include('components.home')
@include('components.about')
@include('components.service')
@include('components.portfolio')
@include('components.contact')
@include('components.footer')
